// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertIdentity = `-- name: UpsertIdentity :one
INSERT INTO identity (first_name, last_name, type, email)
VALUES ($1, $2, $3, $4)
ON CONFLICT (email) DO UPDATE
    SET email      = excluded.email,
        first_name = excluded.first_name,
        last_name  = excluded.last_name
RETURNING id, first_name, last_name, type, email, created_at, updated_at
`

type UpsertIdentityParams struct {
	FirstName pgtype.Text
	LastName  pgtype.Text
	Type      IdentityType
	Email     string
}

func (q *Queries) UpsertIdentity(ctx context.Context, arg UpsertIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, upsertIdentity,
		arg.FirstName,
		arg.LastName,
		arg.Type,
		arg.Email,
	)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Type,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
