// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity_role.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getRolesByIdentityId = `-- name: GetRolesByIdentityId :many
SELECT r.name FROM role r
    JOIN identity_role ir ON ir.role_id = r.id
              WHERE ir.identity_id = $1
`

func (q *Queries) GetRolesByIdentityId(ctx context.Context, identityID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getRolesByIdentityId, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRoleByIdentityId = `-- name: UpsertRoleByIdentityId :one
WITH inserted AS (
    INSERT INTO identity_role(role_id, identity_id)
        VALUES ((SELECT id from role where role.name = $1), $2) ON CONFLICT (role_id, identity_id) DO NOTHING
        RETURNING role_id
) SELECT r.name from role r JOIN inserted i ON r.id = i.role_id
`

type UpsertRoleByIdentityIdParams struct {
	Name       string
	IdentityID uuid.UUID
}

func (q *Queries) UpsertRoleByIdentityId(ctx context.Context, arg UpsertRoleByIdentityIdParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertRoleByIdentityId, arg.Name, arg.IdentityID)
	var name string
	err := row.Scan(&name)
	return name, err
}
