// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: managed_system.sql

package db

import (
	"context"
)

const createManagedSystem = `-- name: CreateManagedSystem :one
INSERT INTO managed_system(name, connector_url, connector_hash, connector_spec)
VALUES ($1, $2, $3, $4)
RETURNING id, name, connector_url, connector_hash, connector_spec, created_at, updated_at
`

type CreateManagedSystemParams struct {
	Name          string
	ConnectorUrl  string
	ConnectorHash string
	ConnectorSpec []byte
}

func (q *Queries) CreateManagedSystem(ctx context.Context, arg CreateManagedSystemParams) (ManagedSystem, error) {
	row := q.db.QueryRow(ctx, createManagedSystem,
		arg.Name,
		arg.ConnectorUrl,
		arg.ConnectorHash,
		arg.ConnectorSpec,
	)
	var i ManagedSystem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ConnectorUrl,
		&i.ConnectorHash,
		&i.ConnectorSpec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listManagedSystems = `-- name: ListManagedSystems :many
SELECT id, name, connector_url, connector_hash, connector_spec, created_at, updated_at
FROM managed_system
ORDER BY created_at DESC
`

func (q *Queries) ListManagedSystems(ctx context.Context) ([]ManagedSystem, error) {
	rows, err := q.db.Query(ctx, listManagedSystems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManagedSystem
	for rows.Next() {
		var i ManagedSystem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ConnectorUrl,
			&i.ConnectorHash,
			&i.ConnectorSpec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
