// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: managed_system.sql

package db

import (
	"context"
)

const createManagedSystem = `-- name: CreateManagedSystem :one
INSERT INTO managed_system(name, connector_url, connector_hash)
VALUES ($1, $2, $3)
RETURNING id, name, connector_url, connector_hash, created_at, updated_at
`

type CreateManagedSystemParams struct {
	Name          string
	ConnectorUrl  string
	ConnectorHash string
}

func (q *Queries) CreateManagedSystem(ctx context.Context, arg CreateManagedSystemParams) (ManagedSystem, error) {
	row := q.db.QueryRow(ctx, createManagedSystem, arg.Name, arg.ConnectorUrl, arg.ConnectorHash)
	var i ManagedSystem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ConnectorUrl,
		&i.ConnectorHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
