// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type IdentityType string

const (
	IdentityTypeUser IdentityType = "user"
)

func (e *IdentityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IdentityType(s)
	case string:
		*e = IdentityType(s)
	default:
		return fmt.Errorf("unsupported scan type for IdentityType: %T", src)
	}
	return nil
}

type NullIdentityType struct {
	IdentityType IdentityType
	Valid        bool // Valid is true if IdentityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIdentityType) Scan(value interface{}) error {
	if value == nil {
		ns.IdentityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IdentityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIdentityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IdentityType), nil
}

type Identity struct {
	ID        uuid.UUID
	FirstName pgtype.Text
	LastName  pgtype.Text
	Type      IdentityType
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type IdentityRole struct {
	ID         uuid.UUID
	RoleID     uuid.UUID
	IdentityID uuid.UUID
}

type Role struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID         uuid.UUID
	SessionID  string
	IdentityID uuid.UUID
	Active     bool
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}
