// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO session (session_id, identity_id, active, expires_at)
VALUES ($1, $2, TRUE, $3)
RETURNING id, session_id, identity_id, active, created_at, expires_at
`

type CreateSessionParams struct {
	SessionID  string
	IdentityID uuid.UUID
	ExpiresAt  pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.SessionID, arg.IdentityID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.IdentityID,
		&i.Active,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deactivateByIdentityId = `-- name: DeactivateByIdentityId :one
UPDATE session
SET active = FALSE
WHERE identity_id = $1 AND active = TRUE
RETURNING id, session_id, identity_id, active, created_at, expires_at
`

func (q *Queries) DeactivateByIdentityId(ctx context.Context, identityID uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, deactivateByIdentityId, identityID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.IdentityID,
		&i.Active,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deactivateBySessionId = `-- name: DeactivateBySessionId :one
UPDATE session
SET active = FALSE
WHERE session_id = $1
RETURNING id, session_id, identity_id, active, created_at, expires_at
`

func (q *Queries) DeactivateBySessionId(ctx context.Context, sessionID string) (Session, error) {
	row := q.db.QueryRow(ctx, deactivateBySessionId, sessionID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.IdentityID,
		&i.Active,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const findActiveSessionByIdentityId = `-- name: FindActiveSessionByIdentityId :one
SELECT id, session_id, identity_id, active, created_at, expires_at
from session
WHERE identity_id = $1
  AND active = TRUE
`

func (q *Queries) FindActiveSessionByIdentityId(ctx context.Context, identityID uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, findActiveSessionByIdentityId, identityID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.IdentityID,
		&i.Active,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const findBySessionId = `-- name: FindBySessionId :one
SELECT identity.id, identity.first_name, identity.last_name, identity.type, identity.email, identity.created_at, identity.updated_at, session.id, session.session_id, session.identity_id, session.active, session.created_at, session.expires_at
FROM identity
         JOIN session ON session.identity_id = identity.id
WHERE session.session_id = $1
`

type FindBySessionIdRow struct {
	Identity Identity
	Session  Session
}

func (q *Queries) FindBySessionId(ctx context.Context, sessionID string) (FindBySessionIdRow, error) {
	row := q.db.QueryRow(ctx, findBySessionId, sessionID)
	var i FindBySessionIdRow
	err := row.Scan(
		&i.Identity.ID,
		&i.Identity.FirstName,
		&i.Identity.LastName,
		&i.Identity.Type,
		&i.Identity.Email,
		&i.Identity.CreatedAt,
		&i.Identity.UpdatedAt,
		&i.Session.ID,
		&i.Session.SessionID,
		&i.Session.IdentityID,
		&i.Session.Active,
		&i.Session.CreatedAt,
		&i.Session.ExpiresAt,
	)
	return i, err
}
