/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description health status of the service */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description To initiate the authentication process with the specified OAuth provider. Provides the URL for the consent page and sets a state cookie for CSRF protection */
        get: operations["authDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Callback endpoint for handling OAuth provider responses after user authentication. Creates a session and sets the session id cookie with redirect path */
        post: operations["authCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description To logout from user account */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get session id user details */
        get: operations["getUserDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Supported Oauth Providers
         * @enum {string}
         */
        "oauth-providers": "google";
    };
    responses: {
        /** @description Internal Server error */
        "internal-server-error": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message: string;
                };
            };
        };
        /** @description Unprocessable Entity */
        "unprocessable-entity-error": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message: string;
                };
            };
        };
        /** @description Unprocessable Entity */
        "bad-request-error": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message: string;
                };
            };
        };
        /** @description Unauthenticated */
        "unauthenticated-error": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message: string;
                    redirect: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    authDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["schemas"]["oauth-providers"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session already exists, redirect directly */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        redirect: string;
                    };
                };
            };
            /** @description New auth flow initiated, consent URL and state cookie set */
            201: {
                headers: {
                    /** @description CSRF state cookie */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uri */
                        authCodeUrl: string;
                    };
                };
            };
            500: components["responses"]["internal-server-error"];
        };
    };
    authCallback: {
        parameters: {
            query: {
                /** @description Authorization code from OAuth provider */
                code: string;
                /** @description State cookie for CSRF protection */
                state: string;
            };
            header?: never;
            path: {
                provider: components["schemas"]["oauth-providers"];
            };
            cookie?: {
                /** @description CSRF state cookie */
                authState?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Returns the session if the session already exists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        redirect: string;
                    };
                };
            };
            /** @description Creates session and set session cookie */
            201: {
                headers: {
                    /** @description Session cookie */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        redirect: string;
                    };
                };
            };
            422: components["responses"]["unprocessable-entity-error"];
            500: components["responses"]["internal-server-error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            400: components["responses"]["bad-request-error"];
            401: components["responses"]["unauthenticated-error"];
            500: components["responses"]["internal-server-error"];
        };
    };
    getUserDetails: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        firstName: string;
                        lastName: string;
                        email: string;
                        id: string;
                    };
                };
            };
            401: components["responses"]["unauthenticated-error"];
            500: components["responses"]["internal-server-error"];
        };
    };
}
