# $schema=https://golangci-lint.run/jsonschema/golangci.v2.jsonschema.json
version: 2

run:
    timeout: 5m

formatters:
    enable:
        - goimports # import formatting
        - gofumpt # formatting rules

linters:
    enable:
        - errcheck # unchecked errors
        - govet # suspicious constructs
        - staticcheck #  static analysis
        - unused # unused code
        - ineffassign # detects assignments whose value is never used
        - revive # maintained replacement for golint
        - gosec # common security issues
        - wrapcheck # ensures errors are wrapped with context before returning
        - cyclop # limits cyclomatic complexity
        - exhaustruct # if all structure fields are initialized

    settings:
        cyclop:
            max-complexity: 10
        funlen:
            lines: 80
            statements: 50
        revive:
            rules:
                - name: exported # skip "comment on exported..." warnings
                  disabled: true
        exhaustruct:
            exclude:
                - net/http.Cookie
                - github.com/golang-migrate/migrate/v4/database/pgx/v5.Config
                - github.com/jackc/pgx/v5/pgtype.Timestamptz
                - net/http.Server
                - log/slog.HandlerOptions
    exclusions:
        rules:
            - path: (.*_test\.go|.*internal/testutil/.*)
              linters:
                  - wrapcheck
                  - staticcheck
                  - gosec
                  - exhaustruct
                  - errcheck
