version: 3

tasks:
    dev:
        cmds:
            - go tool air
    generate:migration:
        preconditions:
            - sh: test -n "{{.NAME}}"
              msg: 'NAME is required. Usage: task migration:generate NAME=<migration_name>'
        cmds:
            - go run -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.19.1 create -ext sql -dir internal/repository/sql/migration -seq {{.NAME}}
    generate:sqlc:
        preconditions:
            - sh: go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.31.1
              msg: 'Failed to install sqlc@v1.31.1'
        cmds:
            - go tool sqlc generate
            - echo "SQLC generation completed ✨"
    generate:oapi-codegen:
        dir: ..
        cmds:
            - oapi-codegen -config core/oapi-codegen.yaml openapi-spec/openapi.yml
    generate:test-mocks:
        cmds:
            - go tool mockgen -source=internal/contract/runtime_application.go -destination=internal/testutil/runtime_application_mock.go -package=testutil
            - go tool mockgen -source=internal/contract/runtime_remote.go -destination=internal/testutil/runtime_remote_mock.go -package=testutil
            - go tool mockgen -source=internal/contract/runtime_repository.go -destination=internal/testutil/runtime_repository_mock.go -package=testutil
    lint:
        cmds:
            - golangci-lint run
    pretty:
        cmds:
            - gofumpt -l -w .
    setup:
        cmds:
            - go get
            - task: generate:test-mocks
            - task: generate:sqlc
    test:
        deps:
            - task: generate:test-mocks
        cmds:
            - go test ./...
