version: 3

tasks:
    setup:
        dir: ..
        cmds:
            - bun install
    dev:
        cmds:
            - bun run dev
    typecheck:
        cmds:
            - bun run typecheck
    test:
        cmds:
            - bun run test
    lint:
        cmds:
            - bun run lint
    pretty:
        cmds:
            - bun run pretty
    build:
        cmds:
            - bun run build
