version: 3

tasks:
    setup:
        dir: ..
        cmds:
            - bun install
    dev:
        cmds:
            - bun run dev
    typecheck:
        cmds:
            - bun run typecheck
    test:
        cmds:
            - bun run test
    lint:
        cmds:
            - bunx oxlint -c ../oxlint.config.ts src
    build:
        cmds:
            - bun run build
