// Code generated by MockGen. DO NOT EDIT.
// Source: internal/contract/runtime_remote.go
//
// Generated by this command:
//
//	mockgen -source=internal/contract/runtime_remote.go -destination=internal/testutil/runtime_remote_mock.go -package=testutil
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	domain "github.com/open-iga/core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOauth2ClientAdapter is a mock of Oauth2ClientAdapter interface.
type MockOauth2ClientAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockOauth2ClientAdapterMockRecorder
	isgomock struct{}
}

// MockOauth2ClientAdapterMockRecorder is the mock recorder for MockOauth2ClientAdapter.
type MockOauth2ClientAdapterMockRecorder struct {
	mock *MockOauth2ClientAdapter
}

// NewMockOauth2ClientAdapter creates a new mock instance.
func NewMockOauth2ClientAdapter(ctrl *gomock.Controller) *MockOauth2ClientAdapter {
	mock := &MockOauth2ClientAdapter{ctrl: ctrl}
	mock.recorder = &MockOauth2ClientAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOauth2ClientAdapter) EXPECT() *MockOauth2ClientAdapterMockRecorder {
	return m.recorder
}

// FetchOauthUser mocks base method.
func (m *MockOauth2ClientAdapter) FetchOauthUser(ctx context.Context, code string) (*domain.OauthUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOauthUser", ctx, code)
	ret0, _ := ret[0].(*domain.OauthUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOauthUser indicates an expected call of FetchOauthUser.
func (mr *MockOauth2ClientAdapterMockRecorder) FetchOauthUser(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOauthUser", reflect.TypeOf((*MockOauth2ClientAdapter)(nil).FetchOauthUser), ctx, code)
}

// GetConsentDetails mocks base method.
func (m *MockOauth2ClientAdapter) GetConsentDetails(ctx context.Context) (*domain.ConsentDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsentDetails", ctx)
	ret0, _ := ret[0].(*domain.ConsentDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsentDetails indicates an expected call of GetConsentDetails.
func (mr *MockOauth2ClientAdapterMockRecorder) GetConsentDetails(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsentDetails", reflect.TypeOf((*MockOauth2ClientAdapter)(nil).GetConsentDetails), ctx)
}
