// Code generated by MockGen. DO NOT EDIT.
// Source: internal/contract/runtime_application.go
//
// Generated by this command:
//
//	mockgen -source=internal/contract/runtime_application.go -destination=internal/testutil/runtime_application_mock.go -package=testutil
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	domain "github.com/open-iga/core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockLoginService is a mock of LoginService interface.
type MockLoginService struct {
	ctrl     *gomock.Controller
	recorder *MockLoginServiceMockRecorder
	isgomock struct{}
}

// MockLoginServiceMockRecorder is the mock recorder for MockLoginService.
type MockLoginServiceMockRecorder struct {
	mock *MockLoginService
}

// NewMockLoginService creates a new mock instance.
func NewMockLoginService(ctrl *gomock.Controller) *MockLoginService {
	mock := &MockLoginService{ctrl: ctrl}
	mock.recorder = &MockLoginServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginService) EXPECT() *MockLoginServiceMockRecorder {
	return m.recorder
}

// DeactivateSession mocks base method.
func (m *MockLoginService) DeactivateSession(ctx context.Context, sessionId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateSession", ctx, sessionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateSession indicates an expected call of DeactivateSession.
func (mr *MockLoginServiceMockRecorder) DeactivateSession(ctx, sessionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateSession", reflect.TypeOf((*MockLoginService)(nil).DeactivateSession), ctx, sessionId)
}

// GenerateSession mocks base method.
func (m *MockLoginService) GenerateSession(ctx context.Context, provider, authCode string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSession", ctx, provider, authCode)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSession indicates an expected call of GenerateSession.
func (mr *MockLoginServiceMockRecorder) GenerateSession(ctx, provider, authCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSession", reflect.TypeOf((*MockLoginService)(nil).GenerateSession), ctx, provider, authCode)
}

// GetConsentPageDetails mocks base method.
func (m *MockLoginService) GetConsentPageDetails(ctx context.Context, provider string) (*domain.ConsentDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsentPageDetails", ctx, provider)
	ret0, _ := ret[0].(*domain.ConsentDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsentPageDetails indicates an expected call of GetConsentPageDetails.
func (mr *MockLoginServiceMockRecorder) GetConsentPageDetails(ctx, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsentPageDetails", reflect.TypeOf((*MockLoginService)(nil).GetConsentPageDetails), ctx, provider)
}

// ValidateSession mocks base method.
func (m *MockLoginService) ValidateSession(ctx context.Context, sessionId string) (*domain.Identity, *domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSession", ctx, sessionId)
	ret0, _ := ret[0].(*domain.Identity)
	ret1, _ := ret[1].(*domain.Session)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ValidateSession indicates an expected call of ValidateSession.
func (mr *MockLoginServiceMockRecorder) ValidateSession(ctx, sessionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSession", reflect.TypeOf((*MockLoginService)(nil).ValidateSession), ctx, sessionId)
}
