// Code generated by MockGen. DO NOT EDIT.
// Source: internal/contract/runtime_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/contract/runtime_repository.go -destination=internal/testutil/runtime_repository_mock.go -package=testutil
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/open-iga/core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityRepository is a mock of IdentityRepository interface.
type MockIdentityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityRepositoryMockRecorder
	isgomock struct{}
}

// MockIdentityRepositoryMockRecorder is the mock recorder for MockIdentityRepository.
type MockIdentityRepositoryMockRecorder struct {
	mock *MockIdentityRepository
}

// NewMockIdentityRepository creates a new mock instance.
func NewMockIdentityRepository(ctrl *gomock.Controller) *MockIdentityRepository {
	mock := &MockIdentityRepository{ctrl: ctrl}
	mock.recorder = &MockIdentityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityRepository) EXPECT() *MockIdentityRepositoryMockRecorder {
	return m.recorder
}

// FindOrCreate mocks base method.
func (m *MockIdentityRepository) FindOrCreate(ctx context.Context, user *domain.OauthUser) (*domain.Identity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreate", ctx, user)
	ret0, _ := ret[0].(*domain.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreate indicates an expected call of FindOrCreate.
func (mr *MockIdentityRepositoryMockRecorder) FindOrCreate(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreate", reflect.TypeOf((*MockIdentityRepository)(nil).FindOrCreate), ctx, user)
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionRepository) Create(ctx context.Context, identity *domain.Identity) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, identity)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSessionRepositoryMockRecorder) Create(ctx, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRepository)(nil).Create), ctx, identity)
}

// DeactivateByIdentityId mocks base method.
func (m *MockSessionRepository) DeactivateByIdentityId(ctx context.Context, identityId uuid.UUID) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateByIdentityId", ctx, identityId)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeactivateByIdentityId indicates an expected call of DeactivateByIdentityId.
func (mr *MockSessionRepositoryMockRecorder) DeactivateByIdentityId(ctx, identityId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateByIdentityId", reflect.TypeOf((*MockSessionRepository)(nil).DeactivateByIdentityId), ctx, identityId)
}

// DeactivateBySessionId mocks base method.
func (m *MockSessionRepository) DeactivateBySessionId(ctx context.Context, sessionId string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateBySessionId", ctx, sessionId)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeactivateBySessionId indicates an expected call of DeactivateBySessionId.
func (mr *MockSessionRepositoryMockRecorder) DeactivateBySessionId(ctx, sessionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateBySessionId", reflect.TypeOf((*MockSessionRepository)(nil).DeactivateBySessionId), ctx, sessionId)
}

// FindActiveSessionByIdentityId mocks base method.
func (m *MockSessionRepository) FindActiveSessionByIdentityId(ctx context.Context, identityId uuid.UUID) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveSessionByIdentityId", ctx, identityId)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveSessionByIdentityId indicates an expected call of FindActiveSessionByIdentityId.
func (mr *MockSessionRepositoryMockRecorder) FindActiveSessionByIdentityId(ctx, identityId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveSessionByIdentityId", reflect.TypeOf((*MockSessionRepository)(nil).FindActiveSessionByIdentityId), ctx, identityId)
}

// FindBySessionId mocks base method.
func (m *MockSessionRepository) FindBySessionId(ctx context.Context, sessionId string) (*domain.Identity, *domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySessionId", ctx, sessionId)
	ret0, _ := ret[0].(*domain.Identity)
	ret1, _ := ret[1].(*domain.Session)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindBySessionId indicates an expected call of FindBySessionId.
func (mr *MockSessionRepositoryMockRecorder) FindBySessionId(ctx, sessionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySessionId", reflect.TypeOf((*MockSessionRepository)(nil).FindBySessionId), ctx, sessionId)
}
