// Code generated by MockGen. DO NOT EDIT.
// Source: internal/contract/runtime_application.go
//
// Generated by this command:
//
//	mockgen -source=internal/contract/runtime_application.go -destination=internal/testutil/runtime_application_mock.go -package=testutil
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/open-iga/core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// DeactivateSession mocks base method.
func (m *MockAuthService) DeactivateSession(ctx context.Context, sessionId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateSession", ctx, sessionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateSession indicates an expected call of DeactivateSession.
func (mr *MockAuthServiceMockRecorder) DeactivateSession(ctx, sessionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateSession", reflect.TypeOf((*MockAuthService)(nil).DeactivateSession), ctx, sessionId)
}

// GenerateSession mocks base method.
func (m *MockAuthService) GenerateSession(ctx context.Context, provider, authCode string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSession", ctx, provider, authCode)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSession indicates an expected call of GenerateSession.
func (mr *MockAuthServiceMockRecorder) GenerateSession(ctx, provider, authCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSession", reflect.TypeOf((*MockAuthService)(nil).GenerateSession), ctx, provider, authCode)
}

// GetConsentPageDetails mocks base method.
func (m *MockAuthService) GetConsentPageDetails(ctx context.Context, provider string) (*domain.ConsentDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsentPageDetails", ctx, provider)
	ret0, _ := ret[0].(*domain.ConsentDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsentPageDetails indicates an expected call of GetConsentPageDetails.
func (mr *MockAuthServiceMockRecorder) GetConsentPageDetails(ctx, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsentPageDetails", reflect.TypeOf((*MockAuthService)(nil).GetConsentPageDetails), ctx, provider)
}

// GetRoles mocks base method.
func (m *MockAuthService) GetRoles(ctx context.Context, identityId uuid.UUID) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoles", ctx, identityId)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetRoles indicates an expected call of GetRoles.
func (mr *MockAuthServiceMockRecorder) GetRoles(ctx, identityId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoles", reflect.TypeOf((*MockAuthService)(nil).GetRoles), ctx, identityId)
}

// ValidateSession mocks base method.
func (m *MockAuthService) ValidateSession(ctx context.Context, sessionId string) (*domain.Identity, *domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSession", ctx, sessionId)
	ret0, _ := ret[0].(*domain.Identity)
	ret1, _ := ret[1].(*domain.Session)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ValidateSession indicates an expected call of ValidateSession.
func (mr *MockAuthServiceMockRecorder) ValidateSession(ctx, sessionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSession", reflect.TypeOf((*MockAuthService)(nil).ValidateSession), ctx, sessionId)
}

// MockConnectorService is a mock of ConnectorService interface.
type MockConnectorService struct {
	ctrl     *gomock.Controller
	recorder *MockConnectorServiceMockRecorder
	isgomock struct{}
}

// MockConnectorServiceMockRecorder is the mock recorder for MockConnectorService.
type MockConnectorServiceMockRecorder struct {
	mock *MockConnectorService
}

// NewMockConnectorService creates a new mock instance.
func NewMockConnectorService(ctrl *gomock.Controller) *MockConnectorService {
	mock := &MockConnectorService{ctrl: ctrl}
	mock.recorder = &MockConnectorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectorService) EXPECT() *MockConnectorServiceMockRecorder {
	return m.recorder
}

// GetOnboardedConnectorDetails mocks base method.
func (m *MockConnectorService) GetOnboardedConnectorDetails(ctx context.Context, onboardingId string) (*domain.ConnectorValidationResult, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOnboardedConnectorDetails", ctx, onboardingId)
	ret0, _ := ret[0].(*domain.ConnectorValidationResult)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetOnboardedConnectorDetails indicates an expected call of GetOnboardedConnectorDetails.
func (mr *MockConnectorServiceMockRecorder) GetOnboardedConnectorDetails(ctx, onboardingId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOnboardedConnectorDetails", reflect.TypeOf((*MockConnectorService)(nil).GetOnboardedConnectorDetails), ctx, onboardingId)
}

// ValidateByUrl mocks base method.
func (m *MockConnectorService) ValidateByUrl(ctx context.Context, connectorUrl, connectorHash string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateByUrl", ctx, connectorUrl, connectorHash)
	ret0, _ := ret[0].(string)
	return ret0
}

// ValidateByUrl indicates an expected call of ValidateByUrl.
func (mr *MockConnectorServiceMockRecorder) ValidateByUrl(ctx, connectorUrl, connectorHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateByUrl", reflect.TypeOf((*MockConnectorService)(nil).ValidateByUrl), ctx, connectorUrl, connectorHash)
}

// MockManagedSystemService is a mock of ManagedSystemService interface.
type MockManagedSystemService struct {
	ctrl     *gomock.Controller
	recorder *MockManagedSystemServiceMockRecorder
	isgomock struct{}
}

// MockManagedSystemServiceMockRecorder is the mock recorder for MockManagedSystemService.
type MockManagedSystemServiceMockRecorder struct {
	mock *MockManagedSystemService
}

// NewMockManagedSystemService creates a new mock instance.
func NewMockManagedSystemService(ctrl *gomock.Controller) *MockManagedSystemService {
	mock := &MockManagedSystemService{ctrl: ctrl}
	mock.recorder = &MockManagedSystemServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManagedSystemService) EXPECT() *MockManagedSystemServiceMockRecorder {
	return m.recorder
}

// Onboard mocks base method.
func (m *MockManagedSystemService) Onboard(ctx context.Context, connectorOnboardId string) (*domain.ManagedSystem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Onboard", ctx, connectorOnboardId)
	ret0, _ := ret[0].(*domain.ManagedSystem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Onboard indicates an expected call of Onboard.
func (mr *MockManagedSystemServiceMockRecorder) Onboard(ctx, connectorOnboardId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Onboard", reflect.TypeOf((*MockManagedSystemService)(nil).Onboard), ctx, connectorOnboardId)
}
