openapi: '3.0.4'
info:
    title: OpenIGA
    description: Collection of endpoints for OpenIGA
    version: 1.0.0

paths:
    '/api/health':
        $ref: './paths/health.yml'
    '/api/v1/auth/{provider}':
        $ref: './paths/v1-auth-login.yml'
    '/api/v1/auth/{provider}/callback':
        $ref: './paths/v1-auth-callback.yml'
    '/api/v1/auth/logout':
        $ref: './paths/v1-auth-logout.yml'
    '/api/v1/users':
        $ref: './paths/v1-user-details.yml'
